id: P540B9405
initial_creation_type: input
source_metadata:
  title: Haribhadra Series
  language: en
  description: 'Texts by and about the celebrated master of Prajñāpāramitā Haribhadra
    (seng ge bzang po):'
  volume:
    1dc6cacf117f436f92726b487d4bed8f:
      title: Guru Yoga of the Great Learned and Accomplished Ācārya Haribhadra
      parent: Guru Yoga
created_at: '2022-03-01T02:15:54.410851'
last_modified_at: '2022-03-01T02:15:54.410856'
